# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(542, 446))
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 26, 179, 441))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_1 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_1.setContentsMargins(0, 0, 0, 0)
        self.formLayout_1.setObjectName("formLayout_1")
        self.label_l = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_l.setObjectName("label_l")
        self.formLayout_1.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_l)
        self.edit_l = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_l.setObjectName("edit_l")
        self.formLayout_1.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_l)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_D = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_D.setObjectName("label_D")
        self.formLayout_1.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_D)
        self.edit_D = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_D.setObjectName("edit_D")
        self.formLayout_1.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_D)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.label_s = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_s.setObjectName("label_s")
        self.formLayout_1.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_s)
        self.edit_s = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_s.setObjectName("edit_s")
        self.formLayout_1.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_s)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_c = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_c.setObjectName("label_c")
        self.formLayout_1.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_c)
        self.edit_c = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_c.setObjectName("edit_c")
        self.formLayout_1.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.edit_c)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem7)
        self.label_alpha = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_alpha.setObjectName("label_alpha")
        self.formLayout_1.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_alpha)
        self.edit_alpha = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_alpha.setObjectName("edit_alpha")
        self.formLayout_1.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.edit_alpha)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem9)
        self.label_T = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_T.setObjectName("label_T")
        self.formLayout_1.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_T)
        self.edit_T = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_T.setObjectName("edit_T")
        self.formLayout_1.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.edit_T)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(11, QtWidgets.QFormLayout.LabelRole, spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem11)
        self.label_K = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_K.setObjectName("label_K")
        self.formLayout_1.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_K)
        self.edit_K = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_K.setObjectName("edit_K")
        self.formLayout_1.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.edit_K)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(13, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_1.setItem(13, QtWidgets.QFormLayout.FieldRole, spacerItem13)
        self.label_I = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_I.setObjectName("label_I")
        self.formLayout_1.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_I)
        self.edit_I = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.edit_I.setObjectName("edit_I")
        self.formLayout_1.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.edit_I)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 460, 561, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonClear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buttonClear.setObjectName("buttonClear")
        self.gridLayout.addWidget(self.buttonClear, 0, 1, 1, 1)
        self.buttonCaluclate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.buttonCaluclate.setObjectName("buttonCaluclate")
        self.gridLayout.addWidget(self.buttonCaluclate, 0, 0, 1, 1)
        self.label_gridInfo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_gridInfo.setText("")
        self.label_gridInfo.setObjectName("label_gridInfo")
        self.gridLayout.addWidget(self.label_gridInfo, 0, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 30, 651, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.layoutGraph = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.layoutGraph.setContentsMargins(0, 0, 0, 0)
        self.layoutGraph.setObjectName("layoutGraph")
        self.sliderImage = QtWidgets.QSlider(self.centralwidget)
        self.sliderImage.setGeometry(QtCore.QRect(210, 50, 20, 381))
        self.sliderImage.setMaximum(0)
        self.sliderImage.setOrientation(QtCore.Qt.Vertical)
        self.sliderImage.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderImage.setObjectName("sliderImage")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 96, 13))
        self.label.setObjectName("label")
        self.label_current_time = QtWidgets.QLabel(self.centralwidget)
        self.label_current_time.setGeometry(QtCore.QRect(180, 0, 131, 16))
        self.label_current_time.setObjectName("label_current_time")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 0, 271, 16))
        self.label_3.setObjectName("label_3")
        self.label_max_t = QtWidgets.QLabel(self.centralwidget)
        self.label_max_t.setGeometry(QtCore.QRect(200, 30, 41, 16))
        self.label_max_t.setObjectName("label_max_t")
        self.label_min_t = QtWidgets.QLabel(self.centralwidget)
        self.label_min_t.setGeometry(QtCore.QRect(200, 430, 41, 16))
        self.label_min_t.setObjectName("label_min_t")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 908, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_l.setText(_translate("MainWindow", "l"))
        self.edit_l.setText(_translate("MainWindow", "4"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.edit_D.setText(_translate("MainWindow", "0.02"))
        self.label_s.setText(_translate("MainWindow", "s"))
        self.edit_s.setText(_translate("MainWindow", "3"))
        self.label_c.setText(_translate("MainWindow", "c"))
        self.edit_c.setText(_translate("MainWindow", "1"))
        self.label_alpha.setText(_translate("MainWindow", "alpha"))
        self.edit_alpha.setText(_translate("MainWindow", "0.08"))
        self.label_T.setText(_translate("MainWindow", "T"))
        self.edit_T.setText(_translate("MainWindow", "10"))
        self.label_K.setText(_translate("MainWindow", "K"))
        self.edit_K.setText(_translate("MainWindow", "10"))
        self.label_I.setText(_translate("MainWindow", "I"))
        self.edit_I.setText(_translate("MainWindow", "10"))
        self.buttonClear.setText(_translate("MainWindow", "Очистить"))
        self.buttonCaluclate.setText(_translate("MainWindow", "Посчитать"))
        self.label.setText(_translate("MainWindow", "Параметры задачи"))
        self.label_current_time.setText(_translate("MainWindow", "Индекс времени k = "))
        self.label_3.setText(_translate("MainWindow", "График зависимости температуры от длины стержня"))
        self.label_max_t.setText(_translate("MainWindow", "0"))
        self.label_min_t.setText(_translate("MainWindow", "0"))
